# Random Number means something that cannot be predicted logically

#Pseudo Random are generated by computer algorithm or mathematical equation

# Generate Random Number

from numpy import random

x = random.randint(100)
print(x)

# Generate Random Float

y = random.rand()
print(y)

# Generate Random Array

arr = random.randint(100, size=(5))

print(arr)

# 2D array

arr2 = random.randint(100 , size=(2,3))
print(arr2)

# Generate Random Float Array

arr = random.rand(5)

print(arr)

# 2D array

arr2 = random.rand(2,3)
print(arr2)

# Generate Random Number from Array

x = random.choice([3,4,5,6])
print(x)

# size to specify size of array

y = random.choice([2,3,4,5,6],size=(2,3))
print(y)


# Data Distribution is a list of all possible values and how often each value occurs

# Random Distribution is a set of random numbers that follow a certain PDF

# Probability Density Function : A function that descibrs a continuous probability

# Probability is set by a number between 0 and 1

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
# sum of p should be 1

print(x)

